In [2]:
import numpy as np

In [7]:
#Create array using numpy
#Create a 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) #Types of array
print(arr1.shape) #Shapes of array
#Reshape
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


array([[1, 2, 3, 4, 5]])

In [8]:
#Two dimension array with row and coloumn
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
#Create some array with in built function
arr1 = np.arange(0,10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr1 = np.arange(0,10,2) # skip one numbers go to the second number
print(arr1)

[0 2 4 6 8]


In [13]:
arr1 = np.arange(0,10,2).reshape(5,1) #create two dimension array
print(arr1)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [15]:
np.ones((3,4)) # 3 rows and 4 columns and all will be 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#Identical Matrix
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
#Attribute of numpy array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array:\n",arr)
print("Shape:\n",arr.shape)
print("Number of dimensions:\n",arr.ndim)
print("Size of this array:\n",arr.size)
print("Data type\n",arr.dtype)
print("Array Type:\n",type(arr))
print("Item size (in bytes):",arr.itemsize)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape:
 (2, 5)
Number of dimensions:
 2
Size of this array:
 10
Data type
 int64
Array Type:
 <class 'numpy.ndarray'>
Item size (in bytes): 8


In [25]:
#Numpy vectorized operation
arr1 = np.array([11,12,13,14,15])
arr2 = np.array([10,20,30,40,50])

#Element wise Addition
print("Addition", arr1+arr2)

# Element Wise substraction
print("Sub",arr1-arr2)

#Element wise Multiplication
print("Mul",arr1*arr2)

#Element Wise Division
print("Div",arr1/arr2)

#Element wise modulas
print("Mod", arr1%arr2)

Addition [21 32 43 54 65]
Sub [  1  -8 -17 -26 -35]
Mul [110 240 390 560 750]
Div [1.1        0.6        0.43333333 0.35       0.3       ]
Mod [ 1 12 13 14 15]


In [27]:
# Universal Function
arr = np.array([2,4,6,8,10])

#Square Root
print("sqrt:",np.sqrt(arr))

#Exponential
print("Exponential:",np.exp(arr))

#Sine
print("Sine:",np.sin(arr))

#Natural Log
print("Natural Log:",np.log(arr))

sqrt: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Sine: [ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
Natural Log: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
